# Configuration for selenium assistant - https://github.com/seleniumhq/selenium-assistant

# Comment to greet any user creating a new issue. Set to `false` to disable
openIssueGreetingComment: >
  ðŸ‘‹ Hi there! Thank you for creating this issue.


  I am the Selenium Assistant Bot ðŸ¤–, I triage issues in this repository.
  If I can't do it, I label it to help maintainers identify issues that need triaging.


  I am an Open Source project ðŸ™Œ, post bugs or ideas [here](https://github.com/SeleniumHQ/selenium-assistant)!

# Is the assistant actively closing any new open issues requesting support or asking questions?
closeQuestionsAndSupportRequests: true

# Strings used by the bot to identify that the issue is a request for support or a question?
# If left empty or `false` the bot won't close any support requests or questions
questionsAndSupportRequestsStrings:
  - ðŸ’¬
  - questions and help

# Comment users get when a support request or question is created as an issue.
closeQuestionsAndSupportRequestsComment: >
  ðŸ’¬ It looks like this is a request for support or a question


  ðŸ’¡ A better way to address this is:


  * ðŸ“« Send questions and support requests to the [Selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

  * ðŸ“® Post them to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium)

  * ðŸ—£ Join us in the [IRC/Slack channel](https://seleniumhq.herokuapp.com/) where the community can help you as well


  If you think this is incorrect, please feel free to open a new issue.


  Thank you for your contributions.

# Issue types that the repo supports. When an issue is created, the heading should be one of these strings (from the issue templates).
issueTypes:
  - ðŸ› Bug report
  - ðŸš€ Feature Proposal
  - ðŸ’¥ Regression Report

closeNotSupportedIssueTypes: true

closeNotSupportedIssueTypesComment: >
  ðŸ’¬ It looks like this is a request for support or a question


  ðŸ’¡ A better way to address this is:


  * ðŸ“« Send questions and support requests to the [Selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

  * ðŸ“® Post them to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium)

  * ðŸ—£ Join us in the [IRC/Slack channel](https://seleniumhq.herokuapp.com/) where the community can help you as well


  If you think this is incorrect, please feel free to open a new issue.


  Thank you for your contributions.
