title = "Configurar Selenium 4 en modo HUB"

[server]
registration-secret = "clave"
host = "localhost"
port = 4444
allow-cors = true
bind-host = false

[sessionqueue]
#18h
session-request-timeout = 64800
session-retry-interval = 5

[distributor]
reject-unsupported-caps = true

[events]
publish = "tcp://*:5558"
subscribe = "tcp://*:5559"

[network]
relax-checks = false
