title = "Configurar Selenium 4 en modo Node"

[server]
    registration-secret = "clave"
    host = "192.168.1.42"
    port = 5555

[node]
    detect-drivers = false
    drain-after-session-count = 0

    [[node.driver-configuration]]
        display-name = "Internet Explorer"
        webdriver-executable = "C:\\tools\\WebDriverServers\\IEDriverServer.exe"
        max-sessions = 1
        stereotype = '{"browserName": "internet explorer", "c:custom-cap":  false, "platformName": "WIN10"}'

    [[node.driver-configuration]]
        display-name = "Firefox"
        webdriver-executable = "C:\\tools\\WebDriverServers\\geckodriver.exe"
        max-sessions = 5
        stereotype = '{"browserName": "firefox", "c:custom-cap":  false, "platformName": "WIN10"}'

    [[node.driver-configuration]]
        display-name = "Chrome"
        webdriver-executable = "C:\\tools\\WebDriverServers\\chromedriver.exe"
        max-sessions = 5
        stereotype = '{"browserName": "chrome", "c:custom-cap":  false, "platformName": "WIN10"}'

    [[node.driver-configuration]]
        display-name = "Edge"
        webdriver-executable = "C:\\tools\\WebDriverServers\\msedgedriver.exe"
        max-sessions = 5
        stereotype = '{"browserName": "MicrosoftEdge", "c:custom-cap":  false, "platformName": "WIN10"}'

    hub = "http://192.168.1.39:4444"
    grid-url = "http://192.168.1.39:4444"

[events]
    publish = "tcp://192.168.1.39:5558"
    subscribe = "tcp://192.168.1.39:5559"
