title = "Configurar Selenium 4 en modo Node"

[server]
    registration-secret = "clave"
    host = "192.168.1.42"
    port = 5556


[node]
    detect-drivers = false

    [[node.driver-configuration]]
        display-name = "Internet Explorer"
        webdriver-executable = "C:\\tools\\WebDriverServers\\IEDriverServer.exe"
        max-sessions = 1
        stereotype = '{"browserName": "internet explorer", "c:custom-cap":  true, "platformName": "WIN10", "se:ieOptions": {"ie.edgechromium":"true", "ie.edgepath": "C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe"}}'

    hub = "http://192.168.1.39:4444"
    grid-url = "http://192.168.1.39:4444"

[events]
    bind = false
    publish = "tcp://192.168.1.39:5558"
    subscribe = "tcp://192.168.1.39:5559"
