name: Generate demo GIF

on: push

jobs:
  generate-gif:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Website to GIF
        uses: PabloLec/website-to-gif@1.0.4
        with:
          url: "https://www.selenium.dev/"
          gif_name: "selenium_site.gif"
      - name: Commit GIF to GH repo
        run: |
          git config --global user.name "Diego Molina"
          git config --global user.email "diemol@users.noreply.github.com"
          git add .
          git commit -m 'Update GIF'
          git push
