name: Run issue 13791

on:
  workflow_dispatch:

env:
  DISPLAY: :99

jobs:
  test_examples:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v4
      - name: Start Xvfb
        if: matrix.os == 'ubuntu-latest'
        run: Xvfb :99 &
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.6
      - name: Run script for issue 13791
        run: |
          cd selenium/issue-13791
          mvn clean test
